"""Initial database schema

Revision ID: 98b568baa82e
Revises: 
Create Date: 2026-08-31 22:07:47.018111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98b568baa82e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('DepartmentID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('DepartmentCode', sa.String(length=20), nullable=False),
    sa.Column('DepartmentName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("TRIM(DepartmentCode) <> ''", name='chk_department_code'),
    sa.CheckConstraint("TRIM(DepartmentName) <> ''", name='chk_department_name'),
    sa.PrimaryKeyConstraint('DepartmentID'),
    sa.UniqueConstraint('DepartmentCode'),
    sa.UniqueConstraint('DepartmentName')
    )
    with op.batch_alter_table('Department', schema=None) as batch_op:
        batch_op.create_index('idx_department_active', ['IsActive'], unique=False)

    op.create_table('Role',
    sa.Column('RoleID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('RoleName', sa.String(length=30), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.CheckConstraint("TRIM(RoleName) <> ''", name='chk_role_name'),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('User',
    sa.Column('UserID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('RoleID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Phone', sa.String(length=15), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("Email LIKE '%%@%%'", name='chk_user_email'),
    sa.CheckConstraint("TRIM(FirstName) <> ''", name='chk_user_first_name'),
    sa.CheckConstraint("TRIM(LastName) <> ''", name='chk_user_last_name'),
    sa.ForeignKeyConstraint(['RoleID'], ['Role.RoleID'], name='fk_user_role', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Phone')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['IsActive'], unique=False)
        batch_op.create_index('idx_user_role', ['RoleID'], unique=False)

    op.create_table('AuditLog',
    sa.Column('AuditID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('Action', sa.String(length=100), nullable=False),
    sa.Column('EntityType', sa.String(length=50), nullable=True),
    sa.Column('EntityID', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('IPAddress', sa.String(length=45), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("TRIM(Action) <> ''", name='chk_audit_action'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='fk_audit_user', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('AuditID')
    )
    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['Action'], unique=False)
        batch_op.create_index('idx_audit_created', ['CreatedAt'], unique=False)
        batch_op.create_index('idx_audit_entity', ['EntityType', 'EntityID'], unique=False)
        batch_op.create_index('idx_audit_user', ['UserID'], unique=False)

    op.create_table('Faculty',
    sa.Column('FacultyID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('DepartmentID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('EmployeeNumber', sa.String(length=30), nullable=False),
    sa.Column('Designation', sa.String(length=100), nullable=False),
    sa.CheckConstraint("TRIM(Designation) <> ''", name='chk_faculty_designation'),
    sa.CheckConstraint("TRIM(EmployeeNumber) <> ''", name='chk_faculty_employee'),
    sa.ForeignKeyConstraint(['DepartmentID'], ['Department.DepartmentID'], name='fk_faculty_department', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='fk_faculty_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FacultyID'),
    sa.UniqueConstraint('EmployeeNumber'),
    sa.UniqueConstraint('UserID')
    )
    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.create_index('idx_faculty_department', ['DepartmentID'], unique=False)

    op.create_table('Notification',
    sa.Column('NotificationID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('Title', sa.String(length=150), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.Column('NotificationType', sa.String(length=30), nullable=False),
    sa.Column('IsRead', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ReadAt', sa.DateTime(), nullable=True),
    sa.CheckConstraint("TRIM(Message) <> ''", name='chk_notification_message'),
    sa.CheckConstraint("TRIM(Title) <> ''", name='chk_notification_title'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='fk_notification_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created', ['CreatedAt'], unique=False)
        batch_op.create_index('idx_notification_read', ['IsRead'], unique=False)
        batch_op.create_index('idx_notification_user', ['UserID'], unique=False)

    op.create_table('Question',
    sa.Column('QuestionID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('CreatedBy', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('QuestionText', sa.Text(), nullable=False),
    sa.Column('QuestionType', sa.String(length=20), nullable=False),
    sa.Column('Marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('Difficulty', sa.String(length=20), nullable=False),
    sa.Column('Explanation', sa.Text(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("Difficulty IN ('Easy', 'Medium', 'Hard')", name='chk_question_difficulty'),
    sa.CheckConstraint("QuestionType IN ('MCQ', 'TrueFalse', 'ShortAnswer', 'Descriptive')", name='chk_question_type'),
    sa.CheckConstraint("TRIM(QuestionText) <> ''", name='chk_question_text'),
    sa.CheckConstraint('Marks > 0', name='chk_question_marks'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], name='fk_question_created_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('QuestionID')
    )
    with op.batch_alter_table('Question', schema=None) as batch_op:
        batch_op.create_index('idx_question_active', ['IsActive'], unique=False)
        batch_op.create_index('idx_question_created_by', ['CreatedBy'], unique=False)
        batch_op.create_index('idx_question_difficulty', ['Difficulty'], unique=False)
        batch_op.create_index('idx_question_type', ['QuestionType'], unique=False)

    op.create_table('Student',
    sa.Column('StudentID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('DepartmentID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('RollNumber', sa.String(length=30), nullable=False),
    sa.Column('EnrollmentNumber', sa.String(length=30), nullable=False),
    sa.Column('Year', sa.SmallInteger(), nullable=False),
    sa.Column('Semester', sa.SmallInteger(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("TRIM(EnrollmentNumber) <> ''", name='chk_student_enrollment'),
    sa.CheckConstraint("TRIM(RollNumber) <> ''", name='chk_student_roll'),
    sa.CheckConstraint('Semester > 0', name='chk_student_semester'),
    sa.CheckConstraint('Year > 0', name='chk_student_year'),
    sa.ForeignKeyConstraint(['DepartmentID'], ['Department.DepartmentID'], name='fk_student_department', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='fk_student_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID'),
    sa.UniqueConstraint('EnrollmentNumber'),
    sa.UniqueConstraint('RollNumber'),
    sa.UniqueConstraint('UserID')
    )
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.create_index('idx_student_department', ['DepartmentID'], unique=False)

    op.create_table('Subject',
    sa.Column('SubjectID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('DepartmentID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('CreatedBy', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('SubjectCode', sa.String(length=30), nullable=False),
    sa.Column('SubjectName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Credits', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("TRIM(SubjectCode) <> ''", name='chk_subject_code'),
    sa.CheckConstraint("TRIM(SubjectName) <> ''", name='chk_subject_name'),
    sa.CheckConstraint('Credits > 0', name='chk_subject_credits'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], name='fk_subject_created_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['DepartmentID'], ['Department.DepartmentID'], name='fk_subject_department', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('SubjectID'),
    sa.UniqueConstraint('SubjectCode')
    )
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.create_index('idx_subject_active', ['IsActive'], unique=False)
        batch_op.create_index('idx_subject_created_by', ['CreatedBy'], unique=False)
        batch_op.create_index('idx_subject_department', ['DepartmentID'], unique=False)

    op.create_table('Exam',
    sa.Column('ExamID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('SubjectID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('CreatedBy', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('Title', sa.String(length=150), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('DurationMinutes', sa.Integer(), nullable=False),
    sa.Column('TotalMarks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('PassMarks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Instructions', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("Status IN ('Draft', 'Published', 'Completed', 'Cancelled')", name='chk_exam_status'),
    sa.CheckConstraint("TRIM(Title) <> ''", name='chk_exam_title'),
    sa.CheckConstraint('DurationMinutes > 0', name='chk_exam_duration'),
    sa.CheckConstraint('PassMarks >= 0 AND PassMarks <= TotalMarks', name='chk_exam_pass_marks'),
    sa.CheckConstraint('TotalMarks > 0', name='chk_exam_total_marks'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], name='fk_exam_created_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['SubjectID'], ['Subject.SubjectID'], name='fk_exam_subject', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ExamID')
    )
    with op.batch_alter_table('Exam', schema=None) as batch_op:
        batch_op.create_index('idx_exam_created_by', ['CreatedBy'], unique=False)
        batch_op.create_index('idx_exam_status', ['Status'], unique=False)
        batch_op.create_index('idx_exam_subject', ['SubjectID'], unique=False)

    op.create_table('QuestionOption',
    sa.Column('OptionID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('QuestionID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('OptionText', sa.String(length=500), nullable=False),
    sa.Column('IsCorrect', sa.Boolean(), nullable=False),
    sa.Column('OptionOrder', sa.Integer(), nullable=False),
    sa.CheckConstraint("TRIM(OptionText) <> ''", name='chk_option_text'),
    sa.CheckConstraint('OptionOrder > 0', name='chk_option_order'),
    sa.ForeignKeyConstraint(['QuestionID'], ['Question.QuestionID'], name='fk_option_question', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OptionID'),
    sa.UniqueConstraint('QuestionID', 'OptionOrder', name='uq_question_option_order')
    )
    with op.batch_alter_table('QuestionOption', schema=None) as batch_op:
        batch_op.create_index('idx_option_question', ['QuestionID'], unique=False)

    op.create_table('CandidateRegistration',
    sa.Column('RegistrationID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ExamID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('StudentID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('RegisteredAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("Status IN ('Registered', 'Cancelled')", name='chk_registration_status'),
    sa.ForeignKeyConstraint(['ExamID'], ['Exam.ExamID'], name='fk_registration_exam', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StudentID'], ['Student.StudentID'], name='fk_registration_student', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('RegistrationID'),
    sa.UniqueConstraint('ExamID', 'StudentID', name='uq_exam_student_registration')
    )
    with op.batch_alter_table('CandidateRegistration', schema=None) as batch_op:
        batch_op.create_index('idx_registration_exam', ['ExamID'], unique=False)
        batch_op.create_index('idx_registration_status', ['Status'], unique=False)
        batch_op.create_index('idx_registration_student', ['StudentID'], unique=False)

    op.create_table('ExamQuestion',
    sa.Column('ExamQuestionID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ExamID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('QuestionID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('QuestionOrder', sa.Integer(), nullable=False),
    sa.Column('Marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.CheckConstraint('Marks > 0', name='chk_exam_question_marks'),
    sa.CheckConstraint('QuestionOrder > 0', name='chk_exam_question_order'),
    sa.ForeignKeyConstraint(['ExamID'], ['Exam.ExamID'], name='fk_exam_question_exam', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['QuestionID'], ['Question.QuestionID'], name='fk_exam_question_question', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ExamQuestionID'),
    sa.UniqueConstraint('ExamID', 'QuestionID', name='uq_exam_question'),
    sa.UniqueConstraint('ExamID', 'QuestionOrder', name='uq_exam_question_order')
    )
    with op.batch_alter_table('ExamQuestion', schema=None) as batch_op:
        batch_op.create_index('idx_exam_question_exam', ['ExamID'], unique=False)
        batch_op.create_index('idx_exam_question_question', ['QuestionID'], unique=False)

    op.create_table('ExamSchedule',
    sa.Column('ScheduleID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ExamID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('StartTime', sa.DateTime(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=False),
    sa.Column('Room', sa.String(length=50), nullable=True),
    sa.Column('MaxAttempts', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.CheckConstraint('EndTime > StartTime', name='chk_schedule_time'),
    sa.CheckConstraint('MaxAttempts > 0', name='chk_schedule_attempts'),
    sa.ForeignKeyConstraint(['ExamID'], ['Exam.ExamID'], name='fk_schedule_exam', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    with op.batch_alter_table('ExamSchedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_active', ['IsActive'], unique=False)
        batch_op.create_index('idx_schedule_exam', ['ExamID'], unique=False)
        batch_op.create_index('idx_schedule_start', ['StartTime'], unique=False)

    op.create_table('ExamAttempt',
    sa.Column('AttemptID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('RegistrationID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('AttemptNumber', sa.Integer(), nullable=False),
    sa.Column('StartedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('SubmittedAt', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.CheckConstraint("Status IN ('InProgress', 'Submitted', 'AutoSubmitted')", name='chk_attempt_status'),
    sa.CheckConstraint('AttemptNumber > 0', name='chk_attempt_number'),
    sa.CheckConstraint('Score IS NULL OR Score >= 0', name='chk_attempt_score'),
    sa.ForeignKeyConstraint(['RegistrationID'], ['CandidateRegistration.RegistrationID'], name='fk_attempt_registration', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('AttemptID'),
    sa.UniqueConstraint('RegistrationID', 'AttemptNumber', name='uq_registration_attempt')
    )
    with op.batch_alter_table('ExamAttempt', schema=None) as batch_op:
        batch_op.create_index('idx_attempt_registration', ['RegistrationID'], unique=False)
        batch_op.create_index('idx_attempt_started', ['StartedAt'], unique=False)
        batch_op.create_index('idx_attempt_status', ['Status'], unique=False)

    op.create_table('Result',
    sa.Column('ResultID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('AttemptID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('TotalMarks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ObtainedMarks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('Percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Grade', sa.String(length=5), nullable=True),
    sa.Column('ResultStatus', sa.String(length=20), nullable=False),
    sa.Column('PublishedAt', sa.DateTime(), nullable=True),
    sa.CheckConstraint("ResultStatus IN ('Pending', 'Pass', 'Fail')", name='chk_result_status'),
    sa.CheckConstraint('ObtainedMarks >= 0 AND ObtainedMarks <= TotalMarks', name='chk_result_obtained_marks'),
    sa.CheckConstraint('Percentage >= 0 AND Percentage <= 100', name='chk_result_percentage'),
    sa.CheckConstraint('TotalMarks >= 0', name='chk_result_total_marks'),
    sa.ForeignKeyConstraint(['AttemptID'], ['ExamAttempt.AttemptID'], name='fk_result_attempt', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ResultID'),
    sa.UniqueConstraint('AttemptID')
    )
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.create_index('idx_result_published', ['PublishedAt'], unique=False)
        batch_op.create_index('idx_result_status', ['ResultStatus'], unique=False)

    op.create_table('StudentAnswer',
    sa.Column('AnswerID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('AttemptID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ExamQuestionID', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('SelectedOptionID', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('AnswerText', sa.Text(), nullable=True),
    sa.Column('MarksObtained', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('AnsweredAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('MarksObtained IS NULL OR MarksObtained >= 0', name='chk_answer_marks'),
    sa.ForeignKeyConstraint(['AttemptID'], ['ExamAttempt.AttemptID'], name='fk_answer_attempt', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ExamQuestionID'], ['ExamQuestion.ExamQuestionID'], name='fk_answer_exam_question', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['SelectedOptionID'], ['QuestionOption.OptionID'], name='fk_answer_option', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('AnswerID'),
    sa.UniqueConstraint('AttemptID', 'ExamQuestionID', name='uq_attempt_exam_question_answer')
    )
    with op.batch_alter_table('StudentAnswer', schema=None) as batch_op:
        batch_op.create_index('idx_answer_attempt', ['AttemptID'], unique=False)
        batch_op.create_index('idx_answer_exam_question', ['ExamQuestionID'], unique=False)
        batch_op.create_index('idx_answer_option', ['SelectedOptionID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('StudentAnswer', schema=None) as batch_op:
        batch_op.drop_index('idx_answer_option')
        batch_op.drop_index('idx_answer_exam_question')
        batch_op.drop_index('idx_answer_attempt')

    op.drop_table('StudentAnswer')
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.drop_index('idx_result_status')
        batch_op.drop_index('idx_result_published')

    op.drop_table('Result')
    with op.batch_alter_table('ExamAttempt', schema=None) as batch_op:
        batch_op.drop_index('idx_attempt_status')
        batch_op.drop_index('idx_attempt_started')
        batch_op.drop_index('idx_attempt_registration')

    op.drop_table('ExamAttempt')
    with op.batch_alter_table('ExamSchedule', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_start')
        batch_op.drop_index('idx_schedule_exam')
        batch_op.drop_index('idx_schedule_active')

    op.drop_table('ExamSchedule')
    with op.batch_alter_table('ExamQuestion', schema=None) as batch_op:
        batch_op.drop_index('idx_exam_question_question')
        batch_op.drop_index('idx_exam_question_exam')

    op.drop_table('ExamQuestion')
    with op.batch_alter_table('CandidateRegistration', schema=None) as batch_op:
        batch_op.drop_index('idx_registration_student')
        batch_op.drop_index('idx_registration_status')
        batch_op.drop_index('idx_registration_exam')

    op.drop_table('CandidateRegistration')
    with op.batch_alter_table('QuestionOption', schema=None) as batch_op:
        batch_op.drop_index('idx_option_question')

    op.drop_table('QuestionOption')
    with op.batch_alter_table('Exam', schema=None) as batch_op:
        batch_op.drop_index('idx_exam_subject')
        batch_op.drop_index('idx_exam_status')
        batch_op.drop_index('idx_exam_created_by')

    op.drop_table('Exam')
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.drop_index('idx_subject_department')
        batch_op.drop_index('idx_subject_created_by')
        batch_op.drop_index('idx_subject_active')

    op.drop_table('Subject')
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.drop_index('idx_student_department')

    op.drop_table('Student')
    with op.batch_alter_table('Question', schema=None) as batch_op:
        batch_op.drop_index('idx_question_type')
        batch_op.drop_index('idx_question_difficulty')
        batch_op.drop_index('idx_question_created_by')
        batch_op.drop_index('idx_question_active')

    op.drop_table('Question')
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_user')
        batch_op.drop_index('idx_notification_read')
        batch_op.drop_index('idx_notification_created')

    op.drop_table('Notification')
    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.drop_index('idx_faculty_department')

    op.drop_table('Faculty')
    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('AuditLog')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_active')

    op.drop_table('User')
    op.drop_table('Role')
    with op.batch_alter_table('Department', schema=None) as batch_op:
        batch_op.drop_index('idx_department_active')

    op.drop_table('Department')
    # ### end Alembic commands ###
